# Inventory Optimization Engine

## Objective

This notebook identifies inventory risks and provides AI-driven inventory recommendations to reduce stockouts, avoid overstocking, and improve inventory efficiency.

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/retail_store_inventory (1).csv")

In [2]:
def stock_status(row):

    if row["Inventory Level"] < row["Demand Forecast"]:
        return "Stockout Risk"

    elif row["Inventory Level"] > row["Demand Forecast"] * 2:
        return "Overstock"

    else:
        return "Healthy"

df["Stock Status"] = df.apply(stock_status, axis=1)

df["Stock Status"].value_counts()

Stock Status
Healthy          35476
Overstock        35039
Stockout Risk     2585
Name: count, dtype: int64

In [3]:
df["Recommended Reorder"] = np.where(
    df["Inventory Level"] < df["Demand Forecast"],
    np.ceil(df["Demand Forecast"] - df["Inventory Level"]),
    0
)

df[[
    "Inventory Level",
    "Demand Forecast",
    "Recommended Reorder"
]].head()

   Inventory Level  Demand Forecast  Recommended Reorder
0              231           135.47                  0.0
1              204           144.04                  0.0
2              102            74.02                  0.0
3              469            62.18                  0.0
4              166             9.26                  0.0

In [4]:
def inventory_action(row):

    if row["Stock Status"] == "Stockout Risk":
        return "Order Immediately"

    elif row["Stock Status"] == "Overstock":
        return "Pause Purchasing"

    else:
        return "Maintain Inventory"

df["Inventory Recommendation"] = df.apply(
    inventory_action,
    axis=1
)

df["Inventory Recommendation"].value_counts()

Inventory Recommendation
Maintain Inventory    35476
Pause Purchasing      35039
Order Immediately      2585
Name: count, dtype: int64

In [5]:
df[[
    "Store ID",
    "Product ID",
    "Inventory Level",
    "Demand Forecast",
    "Stock Status",
    "Recommended Reorder",
    "Inventory Recommendation"
]].head(20)

,Store ID,Product ID,Inventory Level,Demand Forecast,Stock Status,Recommended Reorder,Inventory Recommendation
0,S001,P0001,231,135.47,Healthy,0.0,Maintain Inventory
1,S001,P0002,204,144.04,Healthy,0.0,Maintain Inventory
2,S001,P0003,102,74.02,Healthy,0.0,Maintain Inventory
3,S001,P0004,469,62.18,Overstock,0.0,Pause Purchasing
4,S001,P0005,166,9.26,Overstock,0.0,Pause Purchasing
5,S001,P0006,138,139.82,Stockout Risk,2.0,Order Immediately
6,S001,P0007,359,108.92,Overstock,0.0,Pause Purchasing
7,S001,P0008,380,329.73,Healthy,0.0,Maintain Inventory
8,S001,P0009,183,174.15,Healthy,0.0,Maintain Inventory
9,S001,P0010,108,24.47,Overstock,0.0,Pause Purchasing
10,S001,P0011,258,152.74,Healthy,0.0,Maintain Inventory
11,S001,P0012,66,26.75,Overstock,0.0,Pause Purchasing
12,S001,P0013,96,41.46,Overstock,0.0,Pause Purchasing
13,S001,P0014,193,6.80,Overstock,0.0,Pause Purchasing
14,S001,P0015,379,363.46,Healthy,0.0,Maintain Inventory
15,S001,P0016,363,255.74,Healthy,0.0,Maintain Inventory
16,S001,P0017,318,255.37,Healthy,0.0,Maintain Inventory
17,S001,P0018,241,147.27,Healthy,0.0,Maintain Inventory
18,S001,P0019,352,267.38,Healthy,0.0,Maintain Inventory
19,S001,P0020,274,115.23,Overstock,0.0,Pause Purchasing